repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
        args: [ . ]

#      - id: autoflake
#        name: autoflake
#        entry: autoflake
#        language: system
#        types: [ python ]
#        args: [ . ]
